name: Android CI

on: [push, pull_request]

jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate file name env var
        run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          FileSalad-debug-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/debug/app-debug.apk" "./app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk"

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk


      
