name: Android CI

on: [push, pull_request]

jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > keystore.jks
        
      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:"${{ secrets.KEY_ALIAS }}"
          keyPassword:"${{ vars.KEY_PASSWORD }}"
          keyAlias:"${{ secrets.KEY_ALIAS }}"
          storeFile:keystore.jks
          EOF

      - name: Generate file name env var
        run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          AppName-release-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/release/app-release.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk

      - name: Build release AAB
        run: bash ./gradlew bundleRelease --stacktrace

      - name: Rename AAB 
        run:
          mv "./app/build/outputs/bundle/release/app-release.aab" "./app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab"
      
      - name: Upload release AAB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab    


      
